### ISSUE TITLE
Fast5 files

### ISSUE THREAD

**Issue by theottlo** [GoekeLab/sg-nex-data#1]
Hi, I was wondering whether you could provide the fast5 files for your data. I'm doing some polyA analysis on ONT reads, so I'd like to run tailfindr/nanopolish which requires the signal data.

**Comment by jonathangoeke** [comment]
Hi @theottlo we will upload the fast5 files later

**Comment by cying111** [comment]
Hi @theottlo, the links to the fast5 files are provided now. Thank you. Let us know if you have further questions.

**Comment by theottlo** [comment]
Great, thanks for uploading the files so quickly!
