### ISSUE TITLE
Data Release?

### ISSUE THREAD

**Issue by mikecuoco** [GoekeLab/sg-nex-data#10]
I was hoping to take a look at the raw data of this project. However, the links to the fastq and bam files in `DATA.md` don't appear to be working. Are you waiting for publication for that data to be available, despite your posted preprint?

**Comment by jonathangoeke** [comment]
Hi @mikecuoco the data was available for quite some time already, that seems to be a problem with the links. The data is currently hosted on Dropbox, and I tried to update the links, but that did not solve the problem, so I assume that this is a temporary error on Dropbox. I will post an update here once that is fixed. You can download the data from ENA in the meantime: https://www.ebi.ac.uk/ena/browser/view/PRJEB44348

**Comment by mikecuoco** [comment]
@jonathangoeke oh great! Thank you.
