### ISSUE TITLE
sample_id  SGNex_MCF7-EV_directRNA_replicate2_run1  is duplicate

### ISSUE THREAD

**Issue by aadali** [GoekeLab/sg-nex-data#18]
![image](https://user-images.githubusercontent.com/55375848/147571474-f7cb84bf-24ea-4ca7-9529-582b9418106e.png)
![image](https://user-images.githubusercontent.com/55375848/147571542-20c30976-b526-4afa-b565-741df4581148.png)

I found the same sample_id (SGNex_MCF7-EV_directRNA_replicate2_run1)  in the Sample_information.txt,   but their fastq_ftps is different .  Is this right?

**Comment by cying111** [comment]
Hi @aadali , I believe this has been resolved since our last update release, please feel free to reply back. For now, I will just close it. 

Thank you
