### ISSUE TITLE
questions about data accessions

### ISSUE THREAD

**Issue by defendant602** [GoekeLab/sg-nex-data#3]
Hello, I have watched your presentation on the Nanopore Tech webinar recently. Thanks for the exciting work you've done and the data availability you provided!

I want to do some tests about the gene expression correlation between nanopore data and Illumina data. Could you please provide the accession number of Illumina data set when you mentioned "ENCODE GS20" on the webinar?

Thank you very much!

**Comment by cying111** [comment]
Hi, thank you for your interests in this dataset!  Please see below for the links to the short read data that we have used.

A549
- Rep1: 
https://www.encodeproject.org/files/ENCFF000EJJ/@@download/ENCFF000EJJ.fastq.gz;
https://www.encodeproject.org/files/ENCFF000EJV/@@download/ENCFF000EJV.fastq.gz
- Rep2: 
https://www.encodeproject.org/files/ENCFF000EJW/@@download/ENCFF000EJW.fastq.gz; https://www.encodeproject.org/files/ENCFF000EKB/@@download/ENCFF000EKB.fastq.gz        

HepG2
- Rep1: 
https://www.encodeproject.org/files/ENCFF000FVT/@@download/ENCFF000FVT.fastq.gz;
https://www.encodeproject.org/files/ENCFF000FVU/@@download/ENCFF000FVU.fastq.gz
- Rep2:
https://www.encodeproject.org/files/ENCFF000FVI/@@download/ENCFF000FVI.fastq.gz;
https://www.encodeproject.org/files/ENCFF000FVV/@@download/ENCFF000FVV.fastq.gz

K562
- Rep1:
https://www.encodeproject.org/files/ENCFF001RED/@@download/ENCFF001RED.fastq.gz;
https://www.encodeproject.org/files/ENCFF001RDZ/@@download/ENCFF001RDZ.fastq.gz
- Rep2:
https://www.encodeproject.org/files/ENCFF001REG/@@download/ENCFF001REG.fastq.gz;
https://www.encodeproject.org/files/ENCFF001REF/@@download/ENCFF001REF.fastq.gz

MCF7
- Rep1:
https://www.encodeproject.org/files/ENCFF000HQR/@@download/ENCFF000HQR.fastq.gz;
https://www.encodeproject.org/files/ENCFF000HQP/@@download/ENCFF000HQP.fastq.gz
- Rep2:
https://www.encodeproject.org/files/ENCFF000HQQ/@@download/ENCFF000HQQ.fastq.gz;
https://www.encodeproject.org/files/ENCFF000HRH/@@download/ENCFF000HRH.fastq.gz

Hct116
- Rep1:
end1
https://www.encodeproject.org/files/ENCFF000DKT/@@download/ENCFF000DKT.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DKU/@@download/ENCFF000DKU.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DKV/@@download/ENCFF000DKV.fastq.gz;
end2
https://www.encodeproject.org/files/ENCFF000DKZ/@@download/ENCFF000DKZ.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DLA/@@download/ENCFF000DLA.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DLB/@@download/ENCFF000DLB.fastq.gz
- Rep2:
end1
https://www.encodeproject.org/files/ENCFF000DKW/@@download/ENCFF000DKW.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DKX/@@download/ENCFF000DKX.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DKY/@@download/ENCFF000DKY.fastq.gz;
end2
https://www.encodeproject.org/files/ENCFF000DLC/@@download/ENCFF000DLC.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DLD/@@download/ENCFF000DLD.fastq.gz,
https://www.encodeproject.org/files/ENCFF000DLE/@@download/ENCFF000DLE.fastq.gz
