### ISSUE TITLE
Sequin spike-in reference

### ISSUE THREAD

**Issue by zzare-umd** [GoekeLab/sg-nex-data#45]
Hi,

My advisor, @rob-p, and I are currently utilizing the SG-NEx dataset for the evaluation of our quantification model. In the course of our research, we came across a reference in the paper "https://doi.org/10.1101/2021.04.21.440736," where it is mentioned that, "For a subset of sequencing runs, we included sequin spike-in RNAs with known concentrations that enable the evaluation of transcript discovery and quantification."

We have been searching for resources that provide information about which specific dataset within SG-NEx contains the sequin spike-in data, as well as the corresponding concentrations of these spike-ins. However, our efforts thus far have not yielded the desired information.

Any guidance or information in locating the source or reference that specifies the dataset containing the sequin spike-in data and their respective concentration values within the SG-NEx dataset would be greatly appreciated.

Regards,
Zahra

**Comment by rob-p** [comment]
Hi @jonathangoeke,

  I just wanted to ping back about this.  It would be *super* useful to us (and I think several others using this data), if the sample sheets contained the info about what samples included the spikeins and in which ratios.

Thanks,
Rob

**Comment by cying111** [comment]
Hi @zzare-umd  and @rob-p 

really sorry for getting back so lately! We have updated the sample spreadsheet with one additional column that indicates the spike-in concentration usage and also included a section in data release and access [here](https://github.com/GoekeLab/sg-nex-data#data-release-and-access) with the true concentration file locations. Please check those out and let us know if you have any problems in accessing these files or additional questions regarding spike-in reference!

Thank you!
Ying

**Comment by rob-p** [comment]
Dear Ying,

  Thank you so much! This will be very helpful. And thank you again for curating this amazing dataset and making it available to the community!

Best,
Rob & Zahra

**Comment by cying111** [comment]
You are most welcome!! I will close this issue then and thank you again for using our data resource and providing your feedback!
