### ISSUE TITLE
Number of PCR cycles 

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/sg-nex-data#8]
I went through the Biorxiv print, particularly the methods and supplementary tables but I could not see any info on the number of PCR cycles used.

It seems there quite bit of PCR bias when comparing genes between cDNA and cDNA-PCR. Was. this is no. of cycle-dependent or is more to do with the alignment of genes with repetitive elements?

**Comment by jonathangoeke** [comment]
Hi @callumparr I assume this is related to PCR amplification, but we used the standard PCR protocol so the cycle number is the same I believe

**Comment by callumparr** [comment]
Ah yes was the PCR cycle number I was enquiring about. I looked up the nanopore protocol and says 10-18 cycles but in their own data, they did not go much into bias and then they did not see much up to 10 cycles I think. But from your data, it also seems to be an issue of repetitive elements not so much cycle number that causes large bias when comparing PCR-free and PCR methods.
